<GridLayout>
    canvas.before:
        BorderImage:
            border: 10, 10, 10, 10
            source: "./im/button_white.png"
            pos: self.pos
            size: self.size

<RootWidget>
    GridLayout:
        size_hint: 0.9, 0.9
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        rows: 1
        Label: 
            text: "i dont suffer from insanity, i enjoy it"
            text_size: self.width-20, self.height-20
            valign: "top"
        Label:
            text: "when i was born i was surprised"
            text_size: self.width-20, self.height-20
            valign: "middle"
            halign: "center"
        Label:
            text:"a consultant is someone who takes a subject you unerstand and make it sound confusing"
            text_size: self.width-20, self.height-20
            valign: "bottom"
            halign: "justify"
