<CustomLayout>
    canvas.before:
        Color:
            rgba: 0, 1, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size

<RootWidget>
    CustomLayout:
        AsyncImage:
            source: "https://i.imgur.com/pWewhaG.jpeg"
            size_hint: 1,0.5
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
    CustomLayout:
        AsyncImage:
            source: "https://i.imgur.com/NFdc6NF.png"
            size_hint: 1, 0.5
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
